export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Doctors } from './Doctors/Doctors'
export { default as Nurses } from './Nurses/Nurses'
export { default as MedicalCenters } from './MedicalCenters/MedicalCenters'
export { default as Signup } from './Signup/Signup'
export { default as Signin } from './Signin/Sigin'